version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cassandra_etl_net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker
    volumes:
      - ./data:/data/log_data  # 새로 추가된 부분
    networks:
      - cassandra_etl_net

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_etl_net

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: airflow
  #     POSTGRES_PASSWORD: airflow
  #     POSTGRES_DB: airflow
  #   ports:
  #     - "5432:5432"

  # airflow-init:
  #   image: apache/airflow:2.0.0
  #   container_name: airflow-init
  #   depends_on:
  #     - postgres
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__WEBSERVER__RBAC=True
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  #   entrypoint: ["airflow", "db", "init"]

  # airflow-webserver:
  #   image: apache/airflow:2.0.0
  #   container_name: airflow-webserver
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #   environment:  
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__WEBSERVER__RBAC=True
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  #   command: ["airflow", "webserver"]

  # airflow-scheduler:
  #   image: apache/airflow:2.0.0
  #   container_name: airflow-scheduler
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__WEBSERVER__RBAC=True
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  #   command: ["airflow", "scheduler"]

volumes:
  cassandra_data:

networks:
  cassandra_etl_net:
    external: true
