version: "3.9"
services:
  csv_streamer:
    build: .
    container_name: ld-streamer
    env_file: [ .env ]
    networks: [ cassandra_etl_net ]
    volumes:
      - ../data/log_data/ingest:/app/ingest:ro
    restart: on-failure

  kafka_probe:
    image: confluentinc/cp-kafka:7.2.2
    container_name: ld-kafka-probe
    networks: [ cassandra_etl_net ]
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        for i in {1..60}; do
          kafka-topics --list --bootstrap-server kafka:29092 && exit 0
          echo "waiting kafka... ($$i)"
          sleep 2
        done
        echo "kafka not ready"; exit 1

networks:
  cassandra_etl_net:
    external: true